export const carsData = [
  {
    id: 1,
    brand: "Mahindra",
    model: "Thar",
    year: 2023,
    fuel: "Petrol",
    price: 1549000,
    image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&h=600&fit=crop&crop=center",
    slug: "mahindra-thar-2023",
    description:
      "The Mahindra Thar is an iconic off-road SUV that combines rugged capability with modern comfort. Built for adventure enthusiasts, it features a powerful engine, advanced 4WD system, and distinctive styling that makes it perfect for both city drives and off-road expeditions.",
    specs: {
      engine: "2.0L mStallion TGDi Petrol",
      transmission: "6-Speed Manual / 6-Speed Automatic",
      mileage: "15.2 kmpl",
      seatingCapacity: "4 Seater",
      fuelTankCapacity: "57 Litres",
      groundClearance: "226 mm",
      bootSpace: "N/A",
      safetyRating: "4 Star (Global NCAP)",
    },
  },
  {
    id: 2,
    brand: "BMW",
    model: "X3",
    year: 2024,
    fuel: "Petrol",
    price: 6750000,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&h=600&fit=crop&crop=center",
    slug: "bmw-x3-2024",
    description:
      "The BMW X3 represents the perfect blend of luxury, performance, and versatility. This premium SUV offers exceptional driving dynamics, cutting-edge technology, and sophisticated design that defines the modern luxury vehicle experience.",
    specs: {
      engine: "2.0L Twin Turbo Petrol",
      transmission: "8-Speed Automatic",
      mileage: "14.8 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "65 Litres",
      groundClearance: "204 mm",
      bootSpace: "550 Litres",
      safetyRating: "5 Star (Euro NCAP)",
    },
  },
  {
    id: 3,
    brand: "Audi",
    model: "Q5",
    year: 2023,
    fuel: "Diesel",
    price: 6250000,
    image: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&crop=center",
    slug: "audi-q5-2023",
    description:
      "The Audi Q5 sets new standards in the luxury SUV segment with its progressive design, advanced technology, and superior performance. Experience the perfect harmony of comfort, efficiency, and dynamic driving pleasure.",
    specs: {
      engine: "2.0L TFSI Diesel",
      transmission: "7-Speed S Tronic",
      mileage: "17.9 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "70 Litres",
      groundClearance: "200 mm",
      bootSpace: "520 Litres",
      safetyRating: "5 Star (Euro NCAP)",
    },
  },
  {
    id: 4,
    brand: "Toyota",
    model: "Fortuner",
    year: 2024,
    fuel: "Diesel",
    price: 3688000,
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop&crop=center",
    slug: "toyota-fortuner-2024",
    description:
      "The Toyota Fortuner is a robust and reliable SUV that's built to conquer any terrain. With its commanding presence, spacious interior, and proven reliability, it's the perfect companion for both family adventures and business travels.",
    specs: {
      engine: "2.8L Diesel",
      transmission: "6-Speed Manual / 6-Speed Automatic",
      mileage: "14.2 kmpl",
      seatingCapacity: "7 Seater",
      fuelTankCapacity: "80 Litres",
      groundClearance: "225 mm",
      bootSpace: "296 Litres",
      safetyRating: "5 Star (ASEAN NCAP)",
    },
  },
  {
    id: 5,
    brand: "Hyundai",
    model: "Creta",
    year: 2023,
    fuel: "Petrol",
    price: 1169000,
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&h=600&fit=crop&crop=center",
    slug: "hyundai-creta-2023",
    description:
      "The Hyundai Creta redefines the compact SUV segment with its bold design, feature-rich interior, and efficient performance. It's the perfect blend of style, technology, and value that makes every journey memorable.",
    specs: {
      engine: "1.5L Petrol",
      transmission: "6-Speed Manual / CVT",
      mileage: "17.4 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "50 Litres",
      groundClearance: "190 mm",
      bootSpace: "433 Litres",
      safetyRating: "5 Star (Global NCAP)",
    },
  },
  {
    id: 6,
    brand: "Mercedes-Benz",
    model: "GLC",
    year: 2024,
    fuel: "Petrol",
    price: 6250000,
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&h=600&fit=crop&crop=center",
    slug: "mercedes-benz-glc-2024",
    description:
      "The Mercedes-Benz GLC embodies the pinnacle of luxury and innovation in the SUV segment. With its elegant design, advanced safety features, and exceptional comfort, it delivers an unparalleled driving experience.",
    specs: {
      engine: "2.0L Turbo Petrol",
      transmission: "9-Speed Automatic",
      mileage: "13.9 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "66 Litres",
      groundClearance: "204 mm",
      bootSpace: "550 Litres",
      safetyRating: "5 Star (Euro NCAP)",
    },
  },
  {
    id: 7,
    brand: "Tata",
    model: "Nexon",
    year: 2024,
    fuel: "Electric",
    price: 1599000,
    image: "https://images.unsplash.com/photo-1593941707882-a5bac6861d75?w=800&h=600&fit=crop&crop=center",
    slug: "tata-nexon-2024",
    description:
      "The Tata Nexon EV represents the future of sustainable mobility with its advanced electric powertrain, modern design, and comprehensive safety features. Experience zero-emission driving without compromising on performance.",
    specs: {
      engine: "Electric Motor",
      transmission: "Single Speed Automatic",
      mileage: "312 km range",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "30.2 kWh Battery",
      groundClearance: "209 mm",
      bootSpace: "350 Litres",
      safetyRating: "5 Star (Global NCAP)",
    },
  },
  {
    id: 8,
    brand: "Maruti Suzuki",
    model: "Swift",
    year: 2023,
    fuel: "Petrol",
    price: 599000,
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800&h=600&fit=crop&crop=center",
    slug: "maruti-suzuki-swift-2023",
    description:
      "The Maruti Suzuki Swift continues to be India's favorite hatchback with its sporty design, fuel-efficient engine, and agile handling. Perfect for city commuting and weekend getaways.",
    specs: {
      engine: "1.2L K-Series Petrol",
      transmission: "5-Speed Manual / AMT",
      mileage: "23.2 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "37 Litres",
      groundClearance: "163 mm",
      bootSpace: "268 Litres",
      safetyRating: "2 Star (Global NCAP)",
    },
  },
  {
    id: 9,
    brand: "Honda",
    model: "City",
    year: 2024,
    fuel: "Petrol",
    price: 1199000,
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&h=600&fit=crop&crop=center",
    slug: "honda-city-2024",
    description:
      "The Honda City sets the benchmark in the premium sedan segment with its sophisticated design, advanced features, and refined driving experience. Engineered for those who appreciate elegance and performance.",
    specs: {
      engine: "1.5L i-VTEC Petrol",
      transmission: "6-Speed Manual / CVT",
      mileage: "17.8 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "40 Litres",
      groundClearance: "165 mm",
      bootSpace: "506 Litres",
      safetyRating: "5 Star (ASEAN NCAP)",
    },
  },
  {
    id: 10,
    brand: "Kia",
    model: "Seltos",
    year: 2024,
    fuel: "Petrol",
    price: 1099000,
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&h=600&fit=crop&crop=center",
    slug: "kia-seltos-2024",
    description:
      "The Kia Seltos combines bold design with advanced technology and impressive performance. This compact SUV offers a perfect balance of style, comfort, and capability for modern urban lifestyles.",
    specs: {
      engine: "1.5L Petrol",
      transmission: "6-Speed Manual / CVT",
      mileage: "16.8 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "50 Litres",
      groundClearance: "190 mm",
      bootSpace: "433 Litres",
      safetyRating: "3 Star (Global NCAP)",
    },
  },
  {
    id: 11,
    brand: "Volkswagen",
    model: "Polo",
    year: 2023,
    fuel: "Petrol",
    price: 699000,
    image: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=600&fit=crop&crop=center",
    slug: "volkswagen-polo-2023",
    description:
      "The Volkswagen Polo delivers German engineering excellence in a compact package. Known for its build quality, safety features, and refined driving dynamics that set it apart in the premium hatchback segment.",
    specs: {
      engine: "1.0L TSI Petrol",
      transmission: "6-Speed Manual / 6-Speed Automatic",
      mileage: "18.2 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "45 Litres",
      groundClearance: "165 mm",
      bootSpace: "280 Litres",
      safetyRating: "4 Star (Global NCAP)",
    },
  },
  {
    id: 12,
    brand: "Skoda",
    model: "Kushaq",
    year: 2024,
    fuel: "Petrol",
    price: 1199000,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop&crop=center",
    slug: "skoda-kushaq-2024",
    description:
      "The Skoda Kushaq brings European design and engineering to the Indian compact SUV market. With its spacious interior, advanced safety features, and dynamic performance, it's built for the discerning Indian customer.",
    specs: {
      engine: "1.0L TSI Petrol",
      transmission: "6-Speed Manual / 6-Speed Automatic",
      mileage: "18.9 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "50 Litres",
      groundClearance: "188 mm",
      bootSpace: "385 Litres",
      safetyRating: "5 Star (Global NCAP)",
    },
  },
  {
    id: 13,
    brand: "Nissan",
    model: "Magnite",
    year: 2023,
    fuel: "Petrol",
    price: 599000,
    image: "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=800&h=600&fit=crop&crop=center",
    slug: "nissan-magnite-2023",
    description:
      "The Nissan Magnite is a feature-packed compact SUV that offers big car experience in a compact package. With its bold design, spacious interior, and advanced technology, it's perfect for first-time SUV buyers.",
    specs: {
      engine: "1.0L Petrol",
      transmission: "5-Speed Manual / CVT",
      mileage: "20.0 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "40 Litres",
      groundClearance: "205 mm",
      bootSpace: "336 Litres",
      safetyRating: "4 Star (Global NCAP)",
    },
  },
  {
    id: 14,
    brand: "Renault",
    model: "Kiger",
    year: 2024,
    fuel: "Petrol",
    price: 649000,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&h=600&fit=crop&crop=center",
    slug: "renault-kiger-2024",
    description:
      "The Renault Kiger stands out with its distinctive design and practical features. This compact SUV offers excellent value for money with its spacious cabin, modern infotainment system, and efficient engine options.",
    specs: {
      engine: "1.0L Petrol",
      transmission: "5-Speed Manual / CVT",
      mileage: "20.5 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "40 Litres",
      groundClearance: "205 mm",
      bootSpace: "405 Litres",
      safetyRating: "4 Star (Global NCAP)",
    },
  },
  {
    id: 15,
    brand: "MG",
    model: "Hector",
    year: 2024,
    fuel: "Petrol",
    price: 1499000,
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&h=600&fit=crop&crop=center",
    slug: "mg-hector-2024",
    description:
      "The MG Hector is India's first internet car, packed with advanced connectivity features and AI-powered voice commands. This mid-size SUV combines British heritage with modern technology and spacious comfort.",
    specs: {
      engine: "1.5L Turbo Petrol",
      transmission: "6-Speed Manual / CVT",
      mileage: "15.2 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "60 Litres",
      groundClearance: "192 mm",
      bootSpace: "578 Litres",
      safetyRating: "5 Star (Global NCAP)",
    },
  },
  {
    id: 16,
    brand: "Jeep",
    model: "Compass",
    year: 2024,
    fuel: "Diesel",
    price: 1999000,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=600&fit=crop&crop=center",
    slug: "jeep-compass-2024",
    description:
      "The Jeep Compass brings authentic Jeep design and capability to the Indian market. With its rugged build quality, advanced 4x4 system, and premium interior, it's built for both urban adventures and off-road exploration.",
    specs: {
      engine: "2.0L Diesel",
      transmission: "6-Speed Manual / 9-Speed Automatic",
      mileage: "17.1 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "60 Litres",
      groundClearance: "205 mm",
      bootSpace: "438 Litres",
      safetyRating: "5 Star (Global NCAP)",
    },
  },
  {
    id: 17,
    brand: "Ford",
    model: "EcoSport",
    year: 2023,
    fuel: "Petrol",
    price: 899000,
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&h=600&fit=crop&crop=center",
    slug: "ford-ecosport-2023",
    description:
      "The Ford EcoSport pioneered the compact SUV segment in India with its bold design and capable performance. Known for its driving dynamics, build quality, and distinctive styling that appeals to young urban buyers.",
    specs: {
      engine: "1.5L Petrol",
      transmission: "5-Speed Manual / 6-Speed Automatic",
      mileage: "15.9 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "52 Litres",
      groundClearance: "200 mm",
      bootSpace: "334 Litres",
      safetyRating: "4 Star (Global NCAP)",
    },
  },
  {
    id: 18,
    brand: "Mahindra",
    model: "XUV700",
    year: 2024,
    fuel: "Petrol",
    price: 1399000,
    image: "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800&h=600&fit=crop&crop=center",
    slug: "mahindra-xuv700-2024",
    description:
      "The Mahindra XUV700 is a feature-rich premium SUV that combines bold design with advanced technology. Offering both 5 and 7-seater configurations, it's packed with segment-first features and powerful engine options.",
    specs: {
      engine: "2.0L mStallion Turbo Petrol",
      transmission: "6-Speed Manual / 6-Speed Automatic",
      mileage: "13.0 kmpl",
      seatingCapacity: "7 Seater",
      fuelTankCapacity: "60 Litres",
      groundClearance: "200 mm",
      bootSpace: "408 Litres",
      safetyRating: "5 Star (Global NCAP)",
    },
  },
  {
    id: 19,
    brand: "Hyundai",
    model: "Venue",
    year: 2024,
    fuel: "Petrol",
    price: 749000,
    image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&h=600&fit=crop&crop=center",
    slug: "hyundai-venue-2024",
    description:
      "The Hyundai Venue is a feature-packed compact SUV that brings premium technology to an accessible price point. With its connected car features, stylish design, and efficient engines, it's perfect for tech-savvy buyers.",
    specs: {
      engine: "1.2L Petrol",
      transmission: "5-Speed Manual / CVT",
      mileage: "18.2 kmpl",
      seatingCapacity: "5 Seater",
      fuelTankCapacity: "45 Litres",
      groundClearance: "195 mm",
      bootSpace: "350 Litres",
      safetyRating: "3 Star (Global NCAP)",
    },
  },
  {
    id: 20,
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2024,
    fuel: "Diesel",
    price: 1899000,
    image: "https://images.unsplash.com/photo-1562141961-d0a6e2e6e7a8?w=800&h=600&fit=crop&crop=center",
    slug: "toyota-innova-crysta-2024",
    description:
      "The Toyota Innova Crysta remains the gold standard in the MPV segment with its unmatched reliability, spacious interior, and strong resale value. Perfect for large families and commercial use with its proven track record.",
    specs: {
      engine: "2.4L Diesel",
      transmission: "5-Speed Manual / 6-Speed Automatic",
      mileage: "15.6 kmpl",
      seatingCapacity: "8 Seater",
      fuelTankCapacity: "55 Litres",
      groundClearance: "178 mm",
      bootSpace: "300 Litres",
      safetyRating: "5 Star (ASEAN NCAP)",
    },
  },
]

export const getBrands = () => {
  return [...new Set(carsData.map((car) => car.brand))]
}

export const getYears = () => {
  return [...new Set(carsData.map((car) => car.year))].sort((a, b) => b - a)
}

export const getFuelTypes = () => {
  return [...new Set(carsData.map((car) => car.fuel))]
}

export const getCarBySlug = (slug) => {
  return carsData.find((car) => car.slug === slug)
}

export const formatPrice = (price) => {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price)
}
